kontrole/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.main.urls', namespace='main')),
    path('users/', include('core.accounts.urls', namespace='user')),
    path('companies/', include('core.companies.urls', namespace='company')),
    path('persons/', include('modules.persons.urls', namespace='persons')),
    path('finances/', include('modules.finances.urls', namespace='finances')),
]

modules/persons/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from modules.persons import views as v

app_name = 'persons'

urlpatterns = [
     # paymentTerms
     path('paymentTerms/',
          login_required(v.paymentTerms_list),
          name='paymentTerms'),
     path('paymentTerms/add/',
          login_required(v.paymentTerms_add),
          name='paymentTerms_add'),
     path('paymentTerms/<int:pk>/',
          login_required(v.paymentTerms_detail),
          name='paymentTerms_detail'),
     path('paymentTerms/edit/<int:pk>/',
          login_required(v.paymentTerms_edit),
          name='paymentTerms_edit'),
     path('paymentTerms/delete/<int:pk>/',
          login_required(v.PaymentTerms_Delete.as_view()),
          name='paymentTerms_delete'),
     # persons
     path('persons/',
          login_required(v.persons_list),
          name='persons_list'),
     path('persons/add/',
          login_required(v.persons_add),
          name='persons_add'),
     path('persons/<int:pk>/',
          login_required(v.persons_detail),
          name='persons_detail'),
     path('persons/edit/<int:pk>/',
          login_required(v.persons_edit),
          name='persons_edit'),
     path('persons/delete/<int:pk>/',
          login_required(v.Persons_Delete.as_view()),
          name='persons_delete'),
     # seller
     path('sellers/',
          login_required(v.seller_list),
          name='seller_list'),
     path('seller/add/',
          login_required(v.Seller_add.as_view()),
          name='seller_add'),
     path('seller/edit/<int:pk>/',
          login_required(v.Seller_edit.as_view()),
          name='seller_edit'),
     path('seller/delete/<int:pk>/',
          login_required(v.Seller_Delete.as_view()),
          name='seller_delete'),
]

modules/persons/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

from core.companies.models import Company
from modules.finances.models import AnaliticAccount

User = settings.AUTH_USER_MODEL


class Person (models.Model):
    PERSONS_TYPE = (
        ("LP", "LEGAL PERSON"),
        ("NP", "NATURAL PERSON")
    )
    personType = models.CharField(
        _("personType"),
        max_length=2,
        choices=PERSONS_TYPE,
        blank=False,
        null=False
    )
    personName = models.CharField(
        _("personName"),
        max_length=100,
        blank=False,
        null=False
    )
    personNickName = models.CharField(
        _("personNickName"),
        max_length=100,
        blank=True,
        null=True
    )
    personTaxpayerRegistration = models.CharField(
        _("personTaxpayerRegistration"),
        max_length=30,
        blank=True,
        null=True
    )
    personAddress = models.CharField(
        _("personAddress"),
        max_length=100,
        blank=True,
        null=True
    )
    personCity = models.CharField(
        _("personCity"),
        max_length=100,
        blank=True,
        null=True
    )
    personState = models.CharField(
        _("personState"),
        max_length=100,
        blank=True,
        null=True
    )
    personCountry = models.CharField(
        _("personCountry"),
        max_length=100,
        blank=True,
        null=True
    )
    personObs = models.CharField(
        _("personObs"),
        max_length=300,
        blank=True,
        null=True
    )
    active = models.BooleanField(
        default=True
    )
    locked = models.BooleanField(
        default=False
    )
    user_created = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='person_user_created'
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    user_updated = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='person_user_updated'
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('personName',)

    def __str__(self):
        return '{} - {} {}'.format(
            self.personName,
            self.personType,
            self.personTaxpayerRegistration
        )

    def get_absolute_url(self):
        return reverse_lazy(
            'persons:persons_detail', kwargs={'pk': self.pk})


class PersonContact (models.Model):
    CONTACT_TYPE = (
        ("E", "E-MAIL"),
        ("T", "PHONE NUMBER"),
        ("W", "WHATSAPP"),
        ("O", "OTHER")
    )
    contactPerson = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name='contacts'
    )
    contactType = models.CharField(
        _("contactType"),
        max_length=1,
        choices=CONTACT_TYPE,
        blank=False,
        null=False
    )
    contactDescription = models.CharField(
        _("contact"),
        max_length=100,
        blank=False,
        null=False
    )
    contactObs = models.CharField(
        _("contactObs"),
        max_length=300,
        blank=True,
        null=True
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} - {} - {} - {}'.format(
            self.pk,
            self.contactPerson,
            self.contactType,
            self.contactDescription
        )


class PaymentTerms(models.Model):
    paymentTermDescription = models.CharField(
        _("paymentTermDescription"),
        max_length=50
    )
    paymentTermsPercentageSum = models.DecimalField(
        _(""),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    active = models.BooleanField(
        default=True
    )
    locked = models.BooleanField(
        default=False
    )
    user_created = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='paymentTerms_user_created'
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    user_updated = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='paymentTerms_user_updated'
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('paymentTermDescription', 'pk',)

    def __str__(self):
        return self.paymentTermDescription

    def get_absolute_url(self):
        return reverse_lazy(
            'persons:paymentTerms_detail', kwargs={'pk': self.pk})


class PaymentTermsDays(models.Model):
    paymentTerms = models.ForeignKey(
        PaymentTerms,
        on_delete=models.CASCADE,
        related_name='paymentterm')
    paymentTermsDay = models.PositiveSmallIntegerField(
        _("paymentTermsDay"),
        default=0
    )
    paymentTermsPercentage = models.DecimalField(
        _(""),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )

    @property
    def paymentTermsPercentageInPercentage(self):
        return f"{self.paymentTermsPercentage} %"

    @property
    def paymentTermsPercentageToCalculate(self):
        return (self.paymentTermsPercentage/100)

    class Meta:
        ordering = ('paymentTermsDay',)

    def __str__(self):
        return '{} - {} day(s) - {}'.format(
            self.paymentTerms,
            self.paymentTermsDay,
            self.paymentTermsPercentageInPercentage
        )


class PersonSeller (models.Model):
    sellerPerson = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        unique=True,
        related_name='slperson'
    )
    sellerNickname = models.CharField(
        _("sellerNickname"),
        max_length=300,
        unique=True,
        blank=False,
        null=False
    )
    active = models.BooleanField(
        default=True
    )
    locked = models.BooleanField(
        default=False
    )
    user_created = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='seller_user_created'
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    user_updated = models.ForeignKey(
        User,
        on_delete=models.DO_NOTHING,
        related_name='seller_user_updated'
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    class Meta:
        ordering = ('sellerNickname',)

    def __str__(self):
        return '{}'.format(
            self.sellerNickname
        )


class PersonCustomer(models.Model):
    customerPerson = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name='cperson'
    )
    customerFinDiscount = models.DecimalField(
        _("customerFinDiscount"),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    customerPaymentTerms = models.ForeignKey(
        PaymentTerms,
        verbose_name=_("customerPaymentTerms"),
        on_delete=models.PROTECT
    )
    customerAccount = models.ForeignKey(
        AnaliticAccount,
        on_delete=models.PROTECT,
        related_name='customerAccount'
    )
    customerSeller = models.ForeignKey(
        PersonSeller,
        on_delete=models.DO_NOTHING,
        related_name='cseller',
        blank=True,
        null=True
    )
    customerObs = models.CharField(
        _("customerObs"),
        max_length=300,
        blank=True,
        null=True
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )

    @property
    def customerFinDiscountPercentage(self):
        return f"{self.customerFinDiscount} %"

    @property
    def customerFinDiscountCalculate(self):
        return (self.customerFinDiscount/100)

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return '{} - {} of Financial Discount - {}'.format(
            self.customerPerson,
            self.customerFinDiscountPercentage,
            self.customerPaymentTerms
        )


class PersonSupplier(models.Model):
    supllierPerson = models.ForeignKey(
        Person,
        on_delete=models.CASCADE,
        related_name='sperson'
    )
    supllierFinDiscount = models.DecimalField(
        _("supllierFinDiscount"),
        max_digits=5,
        decimal_places=2,
        default=0
    )
    supllierPaymentTerms = models.ForeignKey(
        PaymentTerms,
        verbose_name=_("supllierPaymentTerms"),
        on_delete=models.PROTECT
    )
    supllierAccount = models.ForeignKey(
        AnaliticAccount,
        on_delete=models.PROTECT,
        related_name='supllierAccount'
    )
    supllierObs = models.CharField(
        _("supllierObs"),
        max_length=300,
        blank=True,
        null=True
    )
    date_created = models.DateTimeField(
        auto_now_add=True,
        blank=True,
        null=True
    )
    date_updated = models.DateTimeField(
        auto_now=True,
        blank=True,
        null=True
    )

    @property

modules/persons/templates/persons/persons_detail.html
{% extends "base.html" %}

{% block title %}Persons - Kontrole by Arguo{% endblock title %}

{% block content %}
<div class="row">
    <div class="page-header bg-light pt-1 mb-2">
        <h2 class="text-dark float-start">
            <i class="fa-solid fa-user"></i> Person - {{ object.personName }} <span>{% if object.active is True %}(Active){% else %}(Inactive){% endif %}</span>
        </h2>
        <span class="align-text-bottom float-end">
            <a class="btn btn-danger" href="{% url 'persons:persons_list' %}?active_only=on">
                <i class="fa-solid fa-rotate-left"></i> Return
            </a>
            <a class="btn btn-primary" href="{% url 'persons:persons_edit' object.pk %}">
                <i class="fas fa-edit"></i> Edit
            </a>
        </span>
    </div>
</div>

<div class="row">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-end">Created by</th>
                <td class="text-start">{{ object.user_created }} on {{ object.date_created }}</td>
                <th class="text-end">Last Update by</th>
                <td class="text-start">{{ object.user_updated }} on {{ object.date_updated }}</td>               
            </tr>
        </tbody>
    </table>
</div>
<br/>
<div class="row card">
    <table class="table table-user-information">
        <tbody>
            <tr>
                <th class="text-end">Type</th>
                <td class="text-start">{{ object.get_personType_display }}</td>
                <th class="text-end">Name</th>
                <td colspan="3" class="text-start">{{ object.personName }}</td>
                <th class="text-end">TaxPayer Number</th>
                <td class="text-start">{{ object.personTaxpayerRegistration }}</td>               
            </tr>
            <tr>
                <th class="text-end">Address</th>
                <td colspan="7" class="text-start">
                    {% if object.personAddress %}
                        {{ object.personAddress }}
                    {% endif %}
                </td>
            </tr>
            <tr>                    
                <th class="text-end">City</th>
                <td colspan="2" class="text-start">
                    {% if object.personCity %}
                        {{ object.personCity }}
                    {% endif %}
                </td>
                <th class="text-end">State</th>
                <td class="text-start">
                    {% if object.personState %}
                        {{ object.personState }}
                    {% endif %}
                </td>
                <th class="text-end">Country</th>
                <td colspan="2" class="text-start">
                    {% if object.personCountry %}
                        {{ object.personCountry }}
                    {% endif %}
                </td>                
            </tr>
            <tr>
                <th class="text-end">Obs</th>
                <td colspan="7" class="text-start">
                    {% if object.personObs %}
                        {{ object.personObs }}
                    {% endif %}                    
                </td>            
            </tr>
        </tbody>
    </table>
</div>
<p></p>
{% if object.contacts.all|length == 0 %}
{% else %}
<div class="row card">
    <div class="text-center" style="border-bottom: 1px solid #d3d3d3"><h4 class="px-2">Contacts</h4></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Contact Type</th>
                <th>Description</th>
                <th></th>
                <th>Obs</th>
                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for ctobj in object.contacts.all %}
                <tr>
                    <td>{{ ctobj.get_contactType_display }}</td>
                    <td colspan="2">{{ ctobj.contactDescription }}</td>
                    <td colspan="3">{{ ctobj.contactObs }}</td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
</div>
<p></p>
{% endif %}

{% if object.sperson.all|length == 0 %}
{% else %}
<div class="row card">
    <div class="text-center" style="border-bottom: 1px solid #d3d3d3"><h4 class="px-2">Supplier</h4></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Payment Terms</th>
                <th>Account</th>
                <th class="text-center">Financial Discount</th>
                <th>Obs</th>
            </tr>
        </thead>
        <tbody>
            {% for sobj in object.sperson.all %}
                <tr>
                    <td>{{ sobj.supllierPaymentTerms }}</td>
                    <td>{{ sobj.supllierAccount }}</td>
                    <td class="text-center">{{ sobj.supllierFinDiscountPercentage }}</td>
                    <td>{{ sobj.supplierObs }}</td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
</div>
<p></p>
{% endif %}

{% if object.cperson.all|length == 0 %}
{% else %}
<div class="row card">
    <div class="text-center" style="border-bottom: 1px solid #d3d3d3"><h4 class="px-2">Customer</h4></div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Payment Terms</th>
                <th>Account</th>
                <th class="text-center">Financial Discount</th>
                <th>Obs</th>
            </tr>
        </thead>
        <tbody>
            {% for cobj in object.cperson.all %}
                <tr>
                    <td>{{ cobj.customerPaymentTerms }}</td>
                    <td>{{ cobj.customerAccount }}</td>
                    <td class="text-center">{{ cobj.customerFinDiscountPercentage }}</td>
                    <td>{{ cobj.customerObs }}</td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
</div>
<p></p>
{% endif %}
{% endblock content %}

modules/persons/templates/persons/persons_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Person - Kontrole by Arguo{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table-filter.css' %}">
{% endblock css %}

{% block content %}

<!-- Include head with active and find in template -->
{% with head_title="<i class='fa-solid fa-users'></i> Persons" %}
    {% include "includes/headactive.html" %}
{% endwith %}

<div class="col"></div>
<div class="col col-10">

    {% if object_list %}
    <table class="table table-hover table-responsive" style="z-index:999">
        <thead>
            <tr>
                <th>Type</th>
                <th>Name</th>
                <th style="display: none;">Nick Name</th>
                <th>TaxPayer Number</th>
                <th class="text-center">Contacts</th>
                <th>Relationship</th>
                <th class="text-center">Active</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td class="align-middle">{{ object.get_personType_display }}</td>
                <td class="align-middle">
                    <span
                        data-bs-toggle="tooltip"
                        data-bs-html="true"
                        data-bs-placement="right"
                        data-bs-original-title='
                        <div>
                            <b>Nickname:</b> {{ object.personNickName }}
                        </div>'
                    >
                    {{ object.personName }}
                    </span>
                    {% if user.hierarchy == 3 %}
                    {% else %}
                        {% if object.locked == False %}
                            <span style="display: none;">open</span>
                        {% else %}
                            <span style="display: none;">lock</span>
                            <i class="fa-solid fa-lock" style="color: #8c40d9;"></i>
                        {% endif %}
                    {% endif %}
                </td>
                <td style="display: none;">{{ object.personNickName }}</td>
                <td class="align-middle">{{ object.personTaxpayerRegistration }}</td>
                <td class="text-center align-middle">
                    {% if object.contacts.all|length == 0 %}
                        <span style="display: none;">without contact</span>
                        <i class="fa-regular fa-address-book text-secondary"></i>
                    {% else %}
                        <span style="display: none;">with contact</span>
                        <i class="fa-solid fa-address-book text-success"></i>
                    {% endif %}
                </td>
                <td class="align-middle">
                    {% if object.cperson.all|length == 0 and object.sperson.all|length == 0 %}
                    None
                    {% else %}
                        {% if object.sperson.all|length == 0 %}
                        <span style="display: none;">seller</span>
                        Customer
                        {% else %}
                            {% if object.cperson.all|length == 0 %}
                            Supplier
                            {% else %}
                            Supplier | Customer
                            {% endif %}
                        {% endif %}
                    {% endif %}
                </td>
                <td class="text-center align-middle">
                    {% if object.active is True %}
                        <span style="display: none;">active</span>
                        <i class="fa-solid fa-circle-check text-success"></i>
                    {% else %}
                        <span style="display: none;">inactive</span>
                        <i class="fa-solid fa-circle-xmark text-secondary"></i>
                    {% endif %}
                </td>
                <td class="text-center align-middle">
                    <a href="{{ object.get_absolute_url }}">
                        <i class="fa-solid fa-eye text-secondary"></i>
                    </a>
                    {% if user.hierarchy == 3 and object.locked == True %}
                        <a href="{% url 'persons:persons_edit' object.pk %}">
                            <span style="display: none;">lock</span>
                            <i class="fa-solid fa-lock" style="color: #8c40d9;"></i>
                        </a>
                    {% else %}
                    <a href="{% url 'persons:persons_edit' object.pk %}">
                        <span style="display: none;">open</span>
                        <i class="fa-solid fa-pen-to-square text-primary"></i>
                    </a>
                    <a onclick="return confirm('Are you sure you want to delete the Person *{{ object }}*?');" href="{% url 'persons:persons_delete' object.pk %}">
                        <i class="fa-solid fa-trash-can text-danger"></i>
                    </a>
                    {% endif %}
                </td>
            </tr>            
            {% endfor %}
        </tbody>

    </table>

    {% else %}

        <p class="alert alert-warning">No data on this screen.</p>

    {% endif %}

</div>
<div class="col">
    <div style="bottom:30px; right:30px; position:fixed;">
        <div class="btn-group dropup position-relative float-end">
            <button type="button" class="btn btn-outline-primary btn-lg p-2 rounded-circle text-center" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus p-2"></i>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item btn btn-secondary" href="{% url 'persons:persons_add' %}">
                        <i class="fa-solid fa-plus text-primary"></i> Person
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/table-filter.js' %}"></script>
{% endblock js %}