core/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.accounts import views as v

app_name = 'user'

urlpatterns = [
     path('logout/',
          v.custom_logout,
          name='logout'),
     path('users/',
          login_required(v.user_list),
          name='users'),
     path('user/',
          login_required(v.user_list_to_client),
          name='clientusers'),
     path('users/add',
          login_required(v.user_add),
          name='user_add'),
     path('user/add',
          login_required(v.user_add_to_client),
          name='clientuser_add'),
     path('users/edit/<int:pk>/',
          login_required(v.user_edit),
          name='user_edit'),
     path('user/edit/<int:pk>/',
          login_required(v.user_edit_to_client),
          name='clientuser_edit'),
     path('password/edit/<int:pk>/',
          login_required(v.user_edit_to_user),
          name='useruser_edit'),
     path('users/delete/<int:pk>/',
          login_required(v.User_delete.as_view()),
          name='user_delete'),
     path('user/delete/<int:pk>/',
          login_required(v.User_delete_to_client.as_view()),
          name='clientuser_delete'),
]

core/companies/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.companies import views as v

app_name = 'company'

urlpatterns = [
     path('companies/',
          login_required(v.company_list),
          name='companies'),
     path('companies/add',
          login_required(v.Company_add.as_view()),
          name='company_add'),
     path('companies/edit/<int:pk>/',
          login_required(v.Company_edit.as_view()),
          name='company_edit'),
     path('company/edit/<int:pk>/',
          login_required(v.Company_toClient_edit.as_view()),
          name='clientcompany_edit'),
     path('companies/delete/<int:pk>/',
          login_required(v.Company_delete.as_view()),
          name='company_delete'),
]

core/main/urls.py
from django.urls import path

from core.main import views as v

app_name = 'main'

urlpatterns = [
    path('', v.public_index, name='public_index'),
    path('index', v.index, name='index'),
]

kontrole/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.main.urls', namespace='main')),
    path('users/', include('core.accounts.urls', namespace='user')),
    path('companies/', include('core.companies.urls', namespace='company')),
    path('persons/', include('modules.persons.urls', namespace='persons')),
    path('finances/', include('modules.finances.urls', namespace='finances')),
]

modules/finances/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from modules.finances import views as v

app_name = 'finances'

urlpatterns = [
     # chartOfAccounts
     path('chartOfAccounts/',
          login_required(v.chartOfAccounts_list),
          name='chartOfAccounts'),
     # chartOfAccounts - Sintetic Accounts
     path('chartOfAccounts/sinteticAdd',
          login_required(v.Sintetic_add.as_view()),
          name='sintetic_add'),
     path('chartOfAccounts/sintetic/edit/<int:pk>/',
          login_required(v.Sintetic_edit.as_view()),
          name='sintetic_edit'),
     path('chartOfAccounts/sintetic/delete/<int:pk>/',
          login_required(v.Sintetic_delete.as_view()),
          name='sintetic_delete'),
     # chartOfAccounts - Analitic Accounts
     path('chartOfAccounts/analiticAdd',
          login_required(v.Analitic_add.as_view()),
          name='analitic_add'),
     path('chartOfAccounts/analitic/edit/<int:pk>/',
          login_required(v.Analitic_edit.as_view()),
          name='analitic_edit'),
     path('chartOfAccounts/analitic/delete/<int:pk>/',
          login_required(v.Analitic_delete.as_view()),
          name='analitic_delete'),
     # Document Type
     path('documentType/',
          login_required(v.documentType_list),
          name='documentType_list'),
     path('documentType/Add',
          login_required(v.DocumentType_add.as_view()),
          name='documentType_add'),
     path('documentType/edit/<int:pk>/',
          login_required(v.DocumentType_edit.as_view()),
          name='documentType_edit'),
     path('documentType/delete/<int:pk>/',
          login_required(v.DocumentType_delete.as_view()),
          name='documentType_delete'),
     # Entrys
     path('entrys/',
          login_required(v.entrys_list),
          name='entrys_list'),
     path('entrys/<int:pk>/',
          login_required(v.entrys_detail),
          name='entrys_detail'),
     path('entrys/add/',
          login_required(v.entrys_add),
          name='entrys_add'),
     path('entrys/edit/<int:pk>/',
          login_required(v.entrys_edit),
          name='entrys_edit'),
     path('entrys/delete/<int:pk>/',
          login_required(v.Entrys_delete.as_view()),
          name='entrys_delete'),
]

modules/persons/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from modules.persons import views as v

app_name = 'persons'

urlpatterns = [
     # paymentTerms
     path('paymentTerms/',
          login_required(v.paymentTerms_list),
          name='paymentTerms'),
     path('paymentTerms/add/',
          login_required(v.paymentTerms_add),
          name='paymentTerms_add'),
     path('paymentTerms/<int:pk>/',
          login_required(v.paymentTerms_detail),
          name='paymentTerms_detail'),
     path('paymentTerms/edit/<int:pk>/',
          login_required(v.paymentTerms_edit),
          name='paymentTerms_edit'),
     path('paymentTerms/delete/<int:pk>/',
          login_required(v.PaymentTerms_Delete.as_view()),
          name='paymentTerms_delete'),
     # persons
     path('persons/',
          login_required(v.persons_list),
          name='persons_list'),
     path('persons/add/',
          login_required(v.persons_add),
          name='persons_add'),
     path('persons/<int:pk>/',
          login_required(v.persons_detail),
          name='persons_detail'),
     path('persons/edit/<int:pk>/',
          login_required(v.persons_edit),
          name='persons_edit'),
     path('persons/delete/<int:pk>/',
          login_required(v.Persons_Delete.as_view()),
          name='persons_delete'),
     # seller
     path('sellers/',
          login_required(v.seller_list),
          name='seller_list'),
     path('seller/add/',
          login_required(v.Seller_add.as_view()),
          name='seller_add'),
     path('seller/edit/<int:pk>/',
          login_required(v.Seller_edit.as_view()),
          name='seller_edit'),
     path('seller/delete/<int:pk>/',
          login_required(v.Seller_Delete.as_view()),
          name='seller_delete'),
]

core/main/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render


def public_index(request):
    return render(request, 'public_index.html')


@login_required
def index(request):
    return render(request, 'index.html')

core/main/templates/includes/head.html
{% load static %}
<div class="page-header bg-light pt-1 mb-2 d-flex justify-content-between">
    <div class="form-outline d-flex align-items-center">
        <h2 class="text-dark">{{ head_title }}</h2>
    </div>
    <div class="input-group pb-1" style="width: auto;">
        <div class="form-outline d-flex align-items-center">
            <input id="filterInput" type="search" class="form-control"/>
            <div class="search-input ms-2 text-secondary">
                <i id="searchIcon" class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
    </div>
</div>

core/main/templates/includes/headactive.html
{% load static %}
<div class="page-header bg-light pt-1 mb-2 d-flex justify-content-between">
    <div class="form-outline d-flex align-items-center">
        <h2 class="text-dark">{{ head_title }}</h2>
    </div>
    <div class="input-group pb-1" style="width: auto;">
        <form action="" method="get">
            <div class="form-switch pt-3 me-4" style="display: flex;">
                <label class="form-check-label" for="active_only">Active Only:</label>
                <input class="form-check-input" type="checkbox" name="active_only" id="active_only" style="margin-left: 5px;" {% if active_only %}checked{% endif %} onclick="this.form.submit()">
            </div>
        </form>
        <div class="form-outline d-flex align-items-center">
            <input id="filterInput" type="search" class="form-control"/>
            <div class="search-input ms-2 text-secondary">
                <i id="searchIcon" class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
    </div>
</div>

core/main/templates/includes/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="/index"><img src={% static "images/white-logo.png" %} alt="logo" height="40"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/index">Dashboard</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Persons
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'persons:persons_list' %}?active_only=on"><i class="fa-solid fa-users"></i> Registrations</a></li>
                        <li><a class="dropdown-item" href="{% url 'persons:seller_list' %}?active_only=on"><i class="fa-solid fa-user-tag"></i> Sellers</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'persons:paymentTerms' %}?active_only=on"><i class="fa-solid fa-money-check-dollar"></i> Payment Terms</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Reports</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Commercial
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Buys</a></li>
                        <li><a class="dropdown-item" href="#">Sells</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Inventory</a></li>
                        <li><a class="dropdown-item" href="#">Transformation</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Products</a></li>
                        <li><a class="dropdown-item" href="#">Products Group</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Rendering of Services</a></li>
                        <li><a class="dropdown-item" href="#">Services</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Movement Type</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Reports</a></li>
                    </ul>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Finances
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Bills</a></li>
                        <li><a class="dropdown-item" href="#">Receivable</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'finances:entrys_list' %}"><i class="fa-solid fa-money-bill-transfer"></i> Entrys</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'finances:chartOfAccounts' %}?active_only=on"><i class="fa-solid fa-list-ol"></i> Chart of Accounts</a></li>
                        <li><a class="dropdown-item" href="{% url 'finances:documentType_list' %}?active_only=on"><i class="fa-solid fa-paste"></i> Document Type</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Reports</a></li>
                    </ul>
                </li>
                {% if user.hierarchy == 1 or 2 %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Settings
                    </a>
                    <ul class="dropdown-menu">
                        {% if user.hierarchy == 1 %}
                        <li><a class="dropdown-item" href="{% url 'company:companies' %}"><i class="fa-solid fa-building"></i> Companies</a></li>
                        <li><a class="dropdown-item" href="{% url 'user:users' %}"><i class="fa-solid fa-user-gear"></i> Users</a></li>
                        {% endif %}
                        {% if user.hierarchy == 2 %}
                        <li><a class="dropdown-item" href="{% url 'user:clientusers' %}"><i class="fa-solid fa-user-gear"></i> Users</a></li>
                        {% endif %}
                    </ul>
                </li>
                {% endif %}
            </ul>
            <ul class="d-flex navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        {{ user }} | {{ user.company }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a class="dropdown-item" href="{% url 'user:useruser_edit' user.id %}"><i class="fa-solid fa-key"></i> Change Password</a></li>
                        {% if user.hierarchy == 2 %}
                        <li><a class="dropdown-item" href="{% url 'company:clientcompany_edit' user.company.id %}"><i class="fa-solid fa-building"></i> Company</a></li>
                        {% endif %}
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="{% url 'user:logout' %}"><i class="fa-solid fa-right-from-bracket"></i> Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

core/main/templates/includes/public_nav.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src={% static "images/white-logo.png" %} alt="logo" height="40"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Dropdown link
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="#">Action</a></li>
                        <li><a class="dropdown-item" href="#">Another action</a></li>
                        <li><a class="dropdown-item" href="#">Something else here</a></li>
                    </ul>
                </li>
            </ul>
            <div type="button" class="d-flex btn btn-secondary">
                <a class="link-light link-offset-2 link-underline link-underline-opacity-0" href="{% url 'login' %}"><i class="fa-solid fa-right-to-bracket"></i> Login</a>
            </div>
        </div>
    </div>
</nav>