kontrole/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.main.urls', namespace='main')),
    path('users/', include('core.accounts.urls', namespace='user')),
    path('companies/', include('core.companies.urls', namespace='company')),
    path('persons/', include('modules.persons.urls', namespace='persons')),
    path('finances/', include('modules.finances.urls', namespace='finances')),
]

modules/finances/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from modules.finances import views as v

app_name = 'finances'

urlpatterns = [
     # chartOfAccounts
     path('chartOfAccounts/',
          login_required(v.chartOfAccounts_list),
          name='chartOfAccounts'),
     # chartOfAccounts - Sintetic Accounts
     path('chartOfAccounts/sinteticAdd',
          login_required(v.Sintetic_add.as_view()),
          name='sintetic_add'),
     path('chartOfAccounts/sintetic/edit/<int:pk>/',
          login_required(v.Sintetic_edit.as_view()),
          name='sintetic_edit'),
     path('chartOfAccounts/sintetic/delete/<int:pk>/',
          login_required(v.Sintetic_delete.as_view()),
          name='sintetic_delete'),
     # chartOfAccounts - Analitic Accounts
     path('chartOfAccounts/analiticAdd',
          login_required(v.Analitic_add.as_view()),
          name='analitic_add'),
     path('chartOfAccounts/analitic/edit/<int:pk>/',
          login_required(v.Analitic_edit.as_view()),
          name='analitic_edit'),
     path('chartOfAccounts/analitic/delete/<int:pk>/',
          login_required(v.Analitic_delete.as_view()),
          name='analitic_delete'),
     # Document Type
     path('documentType/',
          login_required(v.documentType_list),
          name='documentType_list'),
     path('documentType/Add',
          login_required(v.DocumentType_add.as_view()),
          name='documentType_add'),
     path('documentType/edit/<int:pk>/',
          login_required(v.DocumentType_edit.as_view()),
          name='documentType_edit'),
     path('documentType/delete/<int:pk>/',
          login_required(v.DocumentType_delete.as_view()),
          name='documentType_delete'),
     # Entrys
     path('entrys/',
          login_required(v.entrys_list),
          name='entrys_list'),
     path('entrys/<int:pk>/',
          login_required(v.entrys_detail),
          name='entrys_detail'),
     path('entrys/add/',
          login_required(v.entrys_add),
          name='entrys_add'),
     path('entrys/edit/<int:pk>/',
          login_required(v.entrys_edit),
          name='entrys_edit'),
     path('entrys/delete/<int:pk>/',
          login_required(v.Entrys_delete.as_view()),
          name='entrys_delete'),
]

modules/finances/views.py
from django.contrib import messages
from django.db.models import ProtectedError
from django.forms import inlineformset_factory
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, UpdateView

from core.main.decorators import audit, lock_verification

from .forms import (AnaliticAccount_Form, DocumentType_Form, Entry_Form,
                    ItemEntry_Form, SinteticAccount_Form)
from .models import (ACCOUNTS_TYPE, AnaliticAccount, DocumentType, Entry,
                     EntryItem, SinteticAccount)

# CHART OF ACCOUNTS - LIST


def chartOfAccounts_list(request):
    template_name = 'chartOfAccounts/chartOfAccounts_list.html'
    active_only = request.GET.get('active_only', 'off') == 'on'

    accountobject = (
        ACCOUNTS_TYPE
    )
    sinteticobject = (
        SinteticAccount.objects.all().
        filter(company=request.user.company).
        order_by('sinteticName',)
    )

    if active_only is True:
        analiticobject = AnaliticAccount.objects.all().filter(
            company=request.user.company,
            active=active_only
        ).order_by('analiticName',)
    else:
        analiticobject = AnaliticAccount.objects.all().filter(
            company=request.user.company
        ).order_by('analiticName',)

    context = (
        {
            'sinteticobject': sinteticobject,
            'analiticobject': analiticobject,
            'accountobject': accountobject,
            'active_only': active_only
        }
    )
    return render(request, template_name, context)


# CHART OF ACCOUNTS - Sintetic Account

class Sintetic_add(CreateView):
    model = SinteticAccount
    form_class = SinteticAccount_Form
    template_name = 'chartOfAccounts/sinteticAccounts_form.html'
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_form_kwargs(self):
        kwargs = super(Sintetic_add, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        sintetic = form.save(commit=False)
        sintetic.company = self.request.user.company
        sintetic.user_created = self.request.user
        sintetic.user_updated = self.request.user
        sintetic = form.save()
        messages.success(
            self.request,
            'Sintetic Account added successfully!',
            'alert-success'
        )
        return super(Sintetic_add, self).form_valid(form)


@method_decorator(lock_verification(SinteticAccount), name='dispatch')
class Sintetic_edit(UpdateView):
    model = SinteticAccount
    form_class = SinteticAccount_Form
    template_name = 'chartOfAccounts/sinteticAccounts_form.html'
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_form_kwargs(self):
        kwargs = super(Sintetic_edit, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        sintetic = form.save(commit=False)
        sintetic.user_updated = self.request.user
        sintetic = form.save()
        messages.success(
            self.request,
            'Sintetic Account successfully modified!',
            'alert-success'
        )
        return super(Sintetic_edit, self).form_valid(form)


@method_decorator(lock_verification(SinteticAccount), name='dispatch')
class Sintetic_delete(DeleteView):
    model = SinteticAccount
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_queryset(self):
        company_user = self.request.user.company
        return SinteticAccount.objects.filter(company=company_user)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.warning(
                request,
                'Sintetic Account successfully deleted!',
                'alert-warning'
            )
        except ProtectedError:
            messages.error(
                request,
                'This Account is being used by some Analitic Account!',
                'alert-danger'
            )
        return redirect(request.META.get('HTTP_REFERER', self.success_url))


# CHART OF ACCOUNTS - Analitic Account

class Analitic_add(CreateView):
    model = AnaliticAccount
    form_class = AnaliticAccount_Form
    template_name = 'chartOfAccounts/analiticAccounts_form.html'
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_form_kwargs(self):
        kwargs = super(Analitic_add, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        analitic = form.save(commit=False)
        analitic.company = self.request.user.company
        analitic.user_created = self.request.user
        analitic.user_updated = self.request.user
        analitic.active = True
        analitic = form.save()
        messages.success(
            self.request,
            'Analitic Account added successfully!',
            'alert-success'
        )
        return super(Analitic_add, self).form_valid(form)


@method_decorator(lock_verification(AnaliticAccount), name='dispatch')
class Analitic_edit(UpdateView):
    model = AnaliticAccount
    form_class = AnaliticAccount_Form
    template_name = 'chartOfAccounts/analiticAccounts_form.html'
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_form_kwargs(self):
        kwargs = super(Analitic_edit, self).get_form_kwargs()
        kwargs.update({'user': self.request.user})
        return kwargs

    def form_valid(self, form):
        analitic = form.save(commit=False)
        analitic.user_updated = self.request.user
        analitic = form.save()
        messages.success(
            self.request,
            'Analitic Account successfully modified!',
            'alert-success'
        )
        return super(Analitic_edit, self).form_valid(form)


@method_decorator(lock_verification(AnaliticAccount), name='dispatch')
class Analitic_delete(DeleteView):
    model = AnaliticAccount
    success_url = reverse_lazy('finances:chartOfAccounts')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def get_queryset(self):
        company_user = self.request.user.company
        return AnaliticAccount.objects.filter(company=company_user)

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        try:
            self.object.delete()
            messages.warning(
                request,
                'Analitic Account successfully deleted!',
                'alert-warning'
            )
        except ProtectedError:
            messages.error(
                request,
                'This Account is being used by some Register!',
                'alert-danger'
            )
        return redirect(request.META.get('HTTP_REFERER', self.success_url))


# Document Type


def documentType_list(request):
    template_name = 'documentType/documentType_list.html'
    active_only = request.GET.get('active_only', 'off') == 'on'

    if active_only is True:
        object = DocumentType.objects.all().filter(
            company=request.user.company,
            active=active_only
        )
    else:
        object = DocumentType.objects.all().filter(
            company=request.user.company
        )

    context = {
        'object_list': object,
        'active_only': active_only
    }
    return render(request, template_name, context)


class DocumentType_add(CreateView):
    model = DocumentType
    form_class = DocumentType_Form
    template_name = 'documentType/documentType_form.html'
    success_url = reverse_lazy('finances:documentType_list')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def form_valid(self, form):
        form_instance = form.save(commit=False)
        form_instance.company = self.request.user.company
        form_instance.user_created = self.request.user
        form_instance.user_updated = self.request.user
        form_instance.active = True
        form_instance = form.save()
        messages.success(
            self.request,
            'Document Type successfully added!',
            'alert-success'
        )
        return super(DocumentType_add, self).form_valid(form)


@method_decorator(lock_verification(DocumentType), name='dispatch')
class DocumentType_edit(UpdateView):
    model = DocumentType
    form_class = DocumentType_Form
    template_name = 'documentType/documentType_form.html'
    success_url = reverse_lazy('finances:documentType_list')

    def get_success_url(self):
        url = super().get_success_url()
        return f"{url}?active_only=on"

    def form_valid(self, form):
        form_instance = form.save(commit=False)
        form_instance.company = self.request.user.company
        form_instance.user_updated = self.request.user
        form_instance = form.save()
        messages.success(
            self.request,
            'Document Type successfully edited!',
            'alert-success'
        )
        return super(DocumentType_edit, self).form_valid(form)


@method_decorator(lock_verification(DocumentType), name='dispatch')

modules/finances/templates/chartOfAccounts/analiticAccounts_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Analitic Account - Kontrole by Arguo{% endblock title %}

{% block content %}

    <div class="page-header bg-light pt-1 mb-2">
        <h2 class="text-dark float-start">
            <i class="fa-solid fa-list-ol"></i>
            {% if object %}
                Edit - Analitic Account
                <br/>
                {{ object.analiticName }}      
            {% else %}
                Add - Analitic Account
            {% endif %}
        </h2>

    </div>

    <div class="col"></div>
    <div class="col col-10 col-md-6">
        <form method="POST" novalidate>
            {% csrf_token %}
                <div class="form-row">
                    <label>
                        <span class="required">Account Type</span>
                    </label>
                    {{ form.sinteticAccounts }}
                    {% for error in form.sinteticAccounts.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                <br/>
                <div class="form-row">
                    <label>
                        <span class="required">Sintetic Account Description</span>
                    </label>
                    {{ form.analiticName }}
                    {% for error in form.analiticName.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                {% if user.hierarchy == 3 %}
                {% else %}
                    <br/>
                    <div class="form-row align-center" style="display: flex;">
                        <span class="pe-2" >Locked:</span>
                        <div class="form-check form-switch">{{ form.locked }}</div>
                        {% for error in form.locked.errors %}
                            <br/>
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                    {% if object %}
                        <br/>
                        <div class="form-row align-center" style="display: flex;">
                            <span class="pe-2" >Active:</span>
                            <div class="form-check form-switch">{{ form.active }}</div>
                            {% for error in form.active.errors %}
                                <br/>
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                        </div>  
                       
                    {% endif %}
                {% endif %}
                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button type="submit" class="btn btn-success"><i class="fa-regular fa-circle-check"></i> Save</button>
                            <span class="float-end">
                                <a href="{% url 'finances:chartOfAccounts' %}?active_only=on" class="btn btn-danger">
                                    <i class="fa-regular fa-circle-xmark"></i> Cancel
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
        </form>
    </div>
    <div class="col"></div>


{% endblock content %}

modules/finances/templates/chartOfAccounts/chartOfAccounts_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Chart Of Accounts - Kontrole by Arguo{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table-filter.css' %}">
{% endblock css %}

{% block content %}

<!-- Include head with active and find in template -->
{% with head_title="<i class='fa-solid fa-list-ol'></i> Chart Of Accounts" %}
    {% include "includes/headactive.html" %}
{% endwith %}

<div class="col"></div>
<div class="col col-10 col-lg-8">

    <table class="table table-hover table-responsive" style="z-index:999">
        <thead>
            <th>Accounts</th>
            <th class="text-center">Active</th>
            <th></th>
            <th></th>
        </thead>
        <tbody>
                {% for id, account in accountobject %}
                <tr class="accounts">
                    <td><b>{{ account }}</b></td>
                    <td class="text-center"><b>-</b></td>
                    <td></td>
                    <td class="text-center"><b>-</b></td>
                </tr>
                    {% for sintetic in sinteticobject %}
                        {% if sintetic.accountsType == id %}
                        <tr class="sintetics">
                            <td>
                                &nbsp;&nbsp;&nbsp;
                                {{ sintetic.sinteticName }}
                                <span style="display: None;">{{ account }}</span>
                                {% if user.hierarchy == 3 %}
                                {% else %}
                                    {% if sintetic.locked == False %}
                                        <span style="display: none;">open</span>
                                    {% else %}
                                        <span style="display: none;">lock</span>
                                        <i class="fa-solid fa-lock" style="color: #8c40d9;"></i>
                                    {% endif %}
                                {% endif %}
                            </td>
                            <td class="text-center">-</td>
                            <td></td>
                            <td class="text-end">
                                {% if user.hierarchy == 3 and sintetic.locked == True %}
                                    <a href="{% url 'finances:sintetic_edit' sintetic.pk %}">
                                        <span style="display: none;">lock</span>
                                        <i class="fa-solid fa-lock" style="color: #8c40d9;"></i>
                                    </a>
                                {% else %}
                                    <a href="{% url 'finances:sintetic_edit' sintetic.pk %}">
                                        <span style="display: none;">open</span>
                                        <i class="fa-solid fa-pen-to-square text-primary"></i>
                                    </a>
                                    <a onclick="return confirm('Are you sure you want to delete the account *{{ sintetic.sinteticName }}*?');" href="{% url 'finances:sintetic_delete' sintetic.pk %}"><i class="fa-solid fa-trash-can text-danger"></i></a>
                                {% endif %}
                            </td>
                        </tr>
                            {% for analitic in analiticobject %}
                                {% if analitic.sinteticAccounts == sintetic %}
                                <tr>
                                    <td class="fst-italic">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                        {{ analitic.analiticName }}
                                        <span style="display: None;">{{ sintetic }}</span>
                                        {% if user.hierarchy == 3 %}
                                        {% else %}
                                            {% if analitic.locked == False %}
                                                <span style="display: none;">open</span>
                                            {% else %}
                                                <span style="display: none;">lock</span>
                                                <i class="fa-solid fa-lock" style="color: #8c40d9;"></i>
                                            {% endif %}
                                        {% endif %}
                                    </td>
                                    <td class="text-center">
                                        {% if analitic.active is True %}
                                            <span style="display: none;">active</span>
                                            <i class="fa-solid fa-circle-check text-success"></i>
                                        {% else %}
                                            <span style="display: none;">inactive</span>
                                            <i class="fa-solid fa-circle-xmark text-secondary"></i>
                                        {% endif %}
                                    </td>
                                    <td></td>
                                    <td class="text-start">
                                        {% if user.hierarchy == 3 and analitic.locked == True %}
                                            <a href="{% url 'finances:analitic_edit' analitic.pk %}">
                                                <span style="display: none;">lock</span>
                                                <i class="fa-solid fa-lock" style="color: #b97cf7;"></i>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'finances:analitic_edit' analitic.pk %}">
                                                <span style="display: none;">open</span>
                                                <i class="fa-regular fa-pen-to-square text-primary"></i>
                                            </a>
                                            <a onclick="return confirm('Are you sure you want to delete the account *{{ analitic.analiticName }}*?');" href="{% url 'finances:analitic_delete' analitic.pk %}"><i class="fa-regular fa-trash-can text-danger"></i></a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endif %}
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                {% endfor %}
        </tbody>
    </table>

</div>
<div class="col">
    <div style="bottom:30px; right:30px; position:fixed;">
        <div class="btn-group dropup position-relative float-end">
            <button type="button" class="btn btn-outline-primary btn-lg p-2 rounded-circle text-center" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus p-2"></i>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item btn btn-secondary" href="{% url 'finances:sintetic_add' %}">
                        <i class="fa-solid fa-plus text-primary"></i> Sintetic Account
                    </a>
                </li>
                <li>
                    <a class="dropdown-item btn btn-secondary" href="{% url 'finances:analitic_add' %}">
                        <i class="fa-solid fa-plus text-primary"></i> Analitic Account
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>
{% endblock content %}

{% block js %}
<script src="{% static 'js/table-filter.js' %}"></script>
{% endblock js %}

modules/finances/templates/chartOfAccounts/sinteticAccounts_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}Sintetic Account - Kontrole by Arguo{% endblock title %}

{% block content %}

    <div class="page-header bg-light pt-1 mb-2">
        <h2 class="text-dark float-start">
            <i class="fa-solid fa-list-ol"></i>
            {% if object %}
                Edit - Sintetic Account
                <br/>
                {{ object.sinteticName }}      
            {% else %}
                Add - Sintetic Account
            {% endif %}
        </h2>

    </div>

    <div class="col"></div>
    <div class="col col-10 col-md-6">
        <form method="POST" novalidate>
            {% csrf_token %}
                <div class="form-row">
                    <label>
                        <span class="required">Account Type</span>
                    </label>
                    {{ form.accountsType }}
                    {% for error in form.accountsType.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                <br/>
                <div class="form-row">
                    <label>
                        <span class="required">Sintetic Account Description</span>
                    </label>
                    {{ form.sinteticName }}
                    {% for error in form.sinteticName.errors %}
                        <span style="color:red">{{ error }}</span>
                    {% endfor %}
                </div>
                {% if user.hierarchy == 3 %}
                {% else %}
                    <br/>
                    <div class="form-row align-center" style="display: flex;">
                        <span class="pe-2" >Locked:</span>
                        <div class="form-check form-switch">{{ form.locked }}</div>
                        {% for error in form.locked.errors %}
                            <br/>
                            <span style="color:red">{{ error }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button type="submit" class="btn btn-success"><i class="fa-regular fa-circle-check"></i> Save</button>
                            <span class="float-end">
                                <a href="{% url 'finances:chartOfAccounts' %}?active_only=on" class="btn btn-danger">
                                    <i class="fa-regular fa-circle-xmark"></i> Cancel
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
        </form>
    </div>
    <div class="col"></div>


{% endblock content %}