core/accounts/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.accounts import views as v

app_name = 'user'

urlpatterns = [
     path('logout/',
          v.custom_logout,
          name='logout'),
     path('users/',
          login_required(v.user_list),
          name='users'),
     path('user/',
          login_required(v.user_list_to_client),
          name='clientusers'),
     path('users/add',
          login_required(v.user_add),
          name='user_add'),
     path('user/add',
          login_required(v.user_add_to_client),
          name='clientuser_add'),
     path('users/edit/<int:pk>/',
          login_required(v.user_edit),
          name='user_edit'),
     path('user/edit/<int:pk>/',
          login_required(v.user_edit_to_client),
          name='clientuser_edit'),
     path('password/edit/<int:pk>/',
          login_required(v.user_edit_to_user),
          name='useruser_edit'),
     path('users/delete/<int:pk>/',
          login_required(v.User_delete.as_view()),
          name='user_delete'),
     path('user/delete/<int:pk>/',
          login_required(v.User_delete_to_client.as_view()),
          name='clientuser_delete'),
]

core/main/urls.py
from django.urls import path

from core.main import views as v

app_name = 'main'

urlpatterns = [
    path('', v.public_index, name='public_index'),
    path('index', v.index, name='index'),
]

kontrole/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('core.main.urls', namespace='main')),
    path('users/', include('core.accounts.urls', namespace='user')),
    path('companies/', include('core.companies.urls', namespace='company')),
    path('persons/', include('modules.persons.urls', namespace='persons')),
    path('finances/', include('modules.finances.urls', namespace='finances')),
]

core/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from core.companies.models import Company


class AUser(AbstractUser):
    email = models.EmailField(unique=True)
    company = models.ForeignKey(
        Company,
        verbose_name=_("company"),
        on_delete=models.CASCADE,
        related_name='users'
        )
    hierarchy = models.PositiveIntegerField(
        validators=[
            MinValueValidator(1),
            MaxValueValidator(3)
        ]
    )

core/accounts/forms.py
from django import forms
from django.contrib import messages
from django.contrib.auth.hashers import make_password
from django.forms import (EmailInput, NumberInput, PasswordInput, Select,
                          TextInput)

from .models import AUser


class AUser_Form(forms.ModelForm):
    confirm_password = forms.CharField(
        widget=PasswordInput(attrs={
            'class': "form-control",
            'style': "max-width: 300px",
            'placeholder': "Confirm your Password"
        })
    )

    class Meta:
        model = AUser
        fields = ['username', 'email', 'password', 'company', 'hierarchy']
        widgets = {
            'username': TextInput(attrs={
                'class': "form-control",
                'style': "max-width: 400",
                'placeholder': "UserName"
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': "max-width: 600px",
                'placeholder': "E-mail"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'style': "max-width: 300px",
                'placeholder': "Password"
            }),
            'company': Select(attrs={
                'class': "form-select",
                'style': "max-width: 200px",
                'placeholder': "Select the User's Company"
            }),
            'hierarchy': NumberInput(attrs={
                'class': "form-control",
                'style': "max-width: 150px",
                'placeholder': "Hierarchy Level"
            }),
        }


class AUser_toClient_Form(forms.ModelForm):
    confirm_password = forms.CharField(
        widget=PasswordInput(attrs={
            'class': "form-control",
            'style': "max-width: 300px",
            'placeholder': "Confirm your Password"
        })
    )

    class Meta:
        model = AUser
        fields = ['username', 'email', 'password']
        widgets = {
            'username': TextInput(attrs={
                'class': "form-control",
                'style': "max-width: 400",
                'placeholder': "UserName"
            }),
            'email': EmailInput(attrs={
                'class': "form-control",
                'style': "max-width: 600px",
                'placeholder': "E-mail"
            }),
            'password': PasswordInput(attrs={
                'class': "form-control",
                'style': "max-width: 300px",
                'placeholder': "Password"
            }),
        }


class AUser_toUser_Form(forms.ModelForm):
    confirm_password = forms.CharField(
        widget=PasswordInput(attrs={
            'class': "form-control",
            'style': "max-width: 300px",
            'placeholder': "Confirm your Password"
        })
    )

    class Meta:
        model = AUser
        fields = ['password']
        widgets = {
            'password': PasswordInput(attrs={
                'class': "form-control",
                'style': "max-width: 300px",
                'placeholder': "Password"
            }),
        }

core/accounts/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.hashers import make_password
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import DeleteView, UpdateView

from core.companies.models import Company
from core.main.decorators import hierarchy_is_1, hierarchy_is_2

from .forms import AUser_Form, AUser_toClient_Form, AUser_toUser_Form
from .models import AUser


def custom_logout(request):
    logout(request)
    return redirect(settings.LOGOUT_REDIRECT_URL)


@hierarchy_is_1
def user_list(request):
    template_name = 'user_list.html'
    object = AUser.objects.all().order_by(
        'company',
        'hierarchy',
        'username',
    )
    context = {'object_list': object}
    return render(request, template_name, context)


@hierarchy_is_2
def user_list_to_client(request):
    template_name = 'user_list_to_client.html'
    object = AUser.objects.all().filter(company=request.user.company).order_by(
        'hierarchy',
        'username',
    )
    context = {'object_list': object}
    return render(request, template_name, context)


@hierarchy_is_1
def user_add(request):
    template_name = 'user_form.html'
    user_form = AUser()

    if request.method == 'POST':
        form = AUser_Form(
            request.POST,
            instance=user_form
        )
        if form.is_valid():
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            if password != confirm_password:
                messages.warning(
                    request,
                    'Passwords do not match!',
                    'alert-warning'
                )
            else:
                form = form.save(commit=False)
                form.password = make_password(password)
                form.save()
                messages.success(
                    request,
                    'User successfully added!',
                    'alert-success'
                )
                return HttpResponseRedirect(
                    reverse_lazy('user:users')
                    )

    else:
        form = AUser_Form(
            instance=user_form
        )

    context = {'form': form}
    return render(request, template_name, context)


@hierarchy_is_2
def user_add_to_client(request):
    template_name = 'user_form_to_client.html'
    user_form = AUser()

    if request.method == 'POST':
        form = AUser_toClient_Form(
            request.POST,
            instance=user_form
        )
        company = request.user.company
        if company.users.count() >= company.usersNumbers:
            messages.error(
                request,
                'This company has already reached the maximum number of allowed users!',
                'alert-error'
            )
            return HttpResponseRedirect(
                reverse_lazy('user:clientusers')
                )
        if form.is_valid():
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            if password != confirm_password:
                messages.warning(
                    request,
                    'Passwords do not match!',
                    'alert-warning'
                )
            else:
                form = form.save(commit=False)
                form.password = make_password(password)
                form.company = company
                form.hierarchy = 3
                form.save()
                messages.success(
                    request,
                    'User successfully added!',
                    'alert-success'
                )
                return HttpResponseRedirect(
                    reverse_lazy('user:clientusers')
                    )

    else:
        form = AUser_toClient_Form(
            instance=user_form
        )

    context = {'form': form}
    return render(request, template_name, context)


@hierarchy_is_1
def user_edit(request, pk):
    template_name = 'user_form.html'
    user_form = AUser.objects.get(pk=pk)

    if request.method == 'POST':
        form = AUser_Form(
            request.POST,
            instance=user_form
        )
        if form.is_valid():
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            if password != confirm_password:
                messages.warning(
                    request,
                    'Passwords do not match!',
                    'alert-warning'
                )
            else:
                form = form.save(commit=False)
                form.password = make_password(password)
                form.save()
                messages.success(
                    request,
                    'User successfully edited!',
                    'alert-success'
                )
                return HttpResponseRedirect(
                    reverse_lazy('user:users')
                    )

    else:
        form = AUser_Form(
            instance=user_form
        )

    context = {'form': form}
    return render(request, template_name, context)


@hierarchy_is_2
def user_edit_to_client(request, pk):
    template_name = 'user_form_to_client.html'
    user_form = AUser.objects.get(pk=pk)

    if request.method == 'POST':
        form = AUser_toClient_Form(
            request.POST,
            instance=user_form
        )
        if form.is_valid():
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            if password != confirm_password:
                messages.warning(
                    request,
                    'Passwords do not match!',
                    'alert-warning'
                )
            else:
                form = form.save(commit=False)
                form.password = make_password(password)
                form.save()
                messages.success(
                    request,
                    'User successfully edited!',
                    'alert-success'
                )
                return HttpResponseRedirect(
                    reverse_lazy('user:clientusers')
                    )

    else:
        form = AUser_toClient_Form(
            instance=user_form
        )

    context = {'form': form}
    return render(request, template_name, context)


def user_edit_to_user(request, pk):
    template_name = 'user_form_to_user.html'
    user_form = AUser.objects.get(pk=pk)

    if request.method == 'POST':
        form = AUser_toUser_Form(
            request.POST,
            instance=user_form
        )
        if form.is_valid():
            password = form.cleaned_data.get('password')
            confirm_password = form.cleaned_data.get('confirm_password')
            if password != confirm_password:
                messages.warning(
                    request,
                    'Passwords do not match!',
                    'alert-warning'
                )
            else:
                form = form.save(commit=False)
                form.password = make_password(password)
                form.save()
                messages.success(
                    request,
                    'Password successfully changed!',
                    'alert-success'
                )
                return HttpResponseRedirect(
                    reverse_lazy('main:index')
                    )

    else:
        form = AUser_toUser_Form(
            instance=user_form
        )

    context = {'form': form}
    return render(request, template_name, context)


@method_decorator(hierarchy_is_1, name='dispatch')
class User_delete(DeleteView):
    model = AUser
    success_url = reverse_lazy('user:users')

    def get(self, request, *args, **kwargs):
        context = messages.warning(
            request,
            'User successfully deleted!',
            'alert-warning'
        )
        return self.delete(context, request, *args, **kwargs)


@method_decorator(hierarchy_is_2, name='dispatch')
class User_delete_to_client(DeleteView):
    model = AUser
    success_url = reverse_lazy('user:clientusers')

    def get(self, request, *args, **kwargs):
        context = messages.warning(
            request,
            'User successfully deleted!',
            'alert-warning'
        )
        return self.delete(context, request, *args, **kwargs)

    def get_queryset(self):
        company_user = self.request.user.company
        return AUser.objects.filter(company=company_user)

core/accounts/templates/user_form.html
{% extends "base.html" %}
{% load static %}

{% block title %}User - Kontrole by Arguo{% endblock title %}

{% block content %}

    <div class="page-header bg-light pt-1 mb-2">
        <h2 class="text-dark float-start">
            <i class="fa-solid fa-user-gear"></i>
            {% if object %}
                Edit - User
                <br/>
                {{ object }}      
            {% else %}
                Add - User
            {% endif %}
        </h2>

    </div>

    <div class="col"></div>
    <div class="col col-10 col-md-8">
        <form method="POST" novalidate>
            {% csrf_token %}
                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-7">
                            <label>
                                <span class="required">UserName</span>
                            </label>
                            {{ form.username }}
                            {% for error in form.username.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                        <div class="form-group col-5">
                            <label>
                                <span class="required">Company</span>
                            </label>
                            {{ form.company }}
                            {% for error in form.company.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-12">
                            <label>
                                <span class="required">E-mail</span>
                            </label>
                            {{ form.email }}
                            {% for error in form.email.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-6">
                            <label>
                                <span class="required">Password</span>
                            </label>
                            {{ form.password }}
                            {% for error in form.password.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                        
                        <div class="form-group col-6">
                            <label>
                                <span class="required">Confirm Password</span>
                            </label>
                            {{ form.confirm_password }}
                            {% for error in form.confirm_password.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="row">
                        <div class="form-group col">
                            <label>
                                <span class="required">Hierarchy</span>
                            </label>
                            {{ form.hierarchy }}
                            {% for error in form.hierarchy.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button type="submit" class="btn btn-success"><i class="fa-regular fa-circle-check"></i> Save</button>
                            <span class="float-end">
                                <a href="{% url 'user:users' %}" class="btn btn-danger">
                                    <i class="fa-regular fa-circle-xmark"></i> Cancel
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
        </form>
    </div>
    <div class="col"></div>


{% endblock content %}

core/accounts/templates/user_form_to_client.html
{% extends "base.html" %}
{% load static %}

{% block title %}User - Kontrole by Arguo{% endblock title %}

{% block content %}

    <div class="page-header bg-light pt-1 mb-2">
        <h2 class="text-dark float-start">
            <i class="fa-solid fa-user-gear"></i>
            {% if object %}
                Edit - User
                <br/>
                {{ object }}      
            {% else %}
                Add - User {{ user.company }}
            {% endif %}
        </h2>

    </div>

    <div class="col"></div>
    <div class="col col-10 col-md-8">
        <form method="POST" novalidate>
            {% csrf_token %}
                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-12">
                            <label>
                                <span class="required">UserName</span>
                            </label>
                            {{ form.username }}
                            {% for error in form.username.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-12">
                            <label>
                                <span class="required">E-mail</span>
                            </label>
                            {{ form.email }}
                            {% for error in form.email.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="form-row">
                    <div class="row">
                        <div class="form-group col-6">
                            <label>
                                <span class="required">Password</span>
                            </label>
                            {{ form.password }}
                            {% for error in form.password.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                        
                        <div class="form-group col-6">
                            <label>
                                <span class="required">Confirm Password</span>
                            </label>
                            {{ form.confirm_password }}
                            {% for error in form.confirm_password.errors %}
                                <span style="color:red">{{ error }}</span>
                            {% endfor %}
                            <br/>
                        </div>
                    </div>
                </div>

                <div class="row float-right">
                    <div class="col-sm-12" style="margin-top: 10px;">
                        <div class="form-inline buttons">
                            <button type="submit" class="btn btn-success"><i class="fa-regular fa-circle-check"></i> Save</button>
                            <span class="float-end">
                                <a href="{% url 'user:clientusers' %}" class="btn btn-danger">
                                    <i class="fa-regular fa-circle-xmark"></i> Cancel
                                </a>
                            </span>
                        </div>
                    </div>
                </div>
        </form>
    </div>
    <div class="col"></div>


{% endblock content %}

core/accounts/templates/user_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}User - Kontrole by Arguo{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table-filter.css' %}">
{% endblock css %}

{% block content %}
<div class="page-header bg-light pt-1 mb-2 d-flex justify-content-between">
    <div>
        <h2 class="text-dark"><i class="fa-solid fa-user-gear"></i> Users</h2>
    </div>
    
    <div class="input-group pb-1" style="width: auto;">
        <div class="form-outline d-flex align-items-center">
            <input id="filterInput" type="search" class="form-control"/>
            <div class="search-input ms-2 text-secondary">
                <i id="searchIcon" class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
    </div>
</div>


<div class="col"></div>
<div class="col col-12 col-lg-8">

    {% if object_list %}
    <table class="table table-hover table-responsive" style="z-index:999">
        <thead>
            <tr>
                <th>Company</th>
                <th>UserName</th>
                <th>E-mail</th>
                <th class="text-center">Hierarchy</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.company }}</td>
                <td>{{ object.username }}</td>
                <td>{{ object.email }}</td>
                <td class="text-center">
                    {% if object.hierarchy == 1 %}
                        admin
                    {% else %}
                        {% if object.hierarchy == 2 %}
                            client
                        {% else %}
                            user
                        {% endif %}
                    {% endif %}
                </td>
                <td class="text-center">
                    <a href="{% url 'user:user_edit' object.pk %}"><i class="fa-solid fa-pen-to-square text-primary"></i></a>
                    <a onclick="return confirm('Are you sure you want to delete the User *{{ object }}*?');" href="{% url 'user:user_delete' object.pk %}"><i class="fa-solid fa-trash-can text-danger"></i></a>
                </td>
            </tr>            
            {% endfor %}
        </tbody>

    </table>

    {% else %}

        <p class="alert alert-warning">No data on this screen.</p>

    {% endif %}

</div>
<div class="col">
    <div style="bottom:30px; right:30px; position:fixed;">
        <div class="btn-group dropup position-relative float-end">
            <button type="button" class="btn btn-outline-primary btn-lg p-2 rounded-circle text-center" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus p-2"></i>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item btn btn-secondary" href="{% url 'user:user_add'%}">
                        <i class="fa-solid fa-plus text-primary"></i> User
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/table-filter.js' %}"></script>

{% endblock js %}

core/accounts/templates/user_list_to_client.html
{% extends "base.html" %}
{% load static %}

{% block title %}User - Kontrole by Arguo{% endblock title %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/table-filter.css' %}">
{% endblock css %}

{% block content %}
<div class="page-header bg-light pt-1 mb-2 d-flex justify-content-between">
    <div>
        <h2 class="text-dark"><i class="fa-solid fa-user-gear"></i> Users - {{ user.company }}</h2>
    </div>
    
    <div class="input-group pb-1" style="width: auto;">
        <div class="form-outline d-flex align-items-center">
            <input id="filterInput" type="search" class="form-control"/>
            <div class="search-input ms-2 text-secondary">
                <i id="searchIcon" class="fa-solid fa-magnifying-glass"></i>
            </div>
        </div>
    </div>
</div>


<div class="col"></div>
<div class="col col-12 col-lg-8">

    {% if object_list %}
    <table class="table table-hover table-responsive" style="z-index:999">
        <thead>
            <tr>
                <th>UserName</th>
                <th>E-mail</th>
                <th class="text-center">Hierarchy</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for object in object_list %}
            <tr>
                <td>{{ object.username }}</td>
                <td>{{ object.email }}</td>
                <td class="text-center">
                    {% if object.hierarchy == 2 %}
                        client
                    {% else %}
                        user
                    {% endif %}
                </td>
                <td class="text-center">
                    <a href="{% url 'user:clientuser_edit' object.pk %}"><i class="fa-solid fa-pen-to-square text-primary"></i></a>
                    <a onclick="return confirm('Are you sure you want to delete the User *{{ object }}*?');" href="{% url 'user:clientuser_delete' object.pk %}"><i class="fa-solid fa-trash-can text-danger"></i></a>
                </td>
            </tr>            
            {% endfor %}
        </tbody>

    </table>

    {% else %}

        <p class="alert alert-warning">No data on this screen.</p>

    {% endif %}

</div>
<div class="col">
    <div style="bottom:30px; right:30px; position:fixed;">
        <div class="btn-group dropup position-relative float-end">
            <button type="button" class="btn btn-outline-primary btn-lg p-2 rounded-circle text-center" data-bs-toggle="dropdown" aria-expanded="false">
                <i class="fa-solid fa-plus p-2"></i>
            </button>
            <ul class="dropdown-menu">
                <li>
                    <a class="dropdown-item btn btn-secondary" href="{% url 'user:clientuser_add'%}">
                        <i class="fa-solid fa-plus text-primary"></i> User
                    </a>
                </li>
            </ul>
        </div>
    </div>
</div>

{% endblock content %}

{% block js %}

<script src="{% static 'js/table-filter.js' %}"></script>

{% endblock js %}